
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'stone_case'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  partitions_to_replace_last_two_days: [
    'current_date("America/Sao_Paulo")'
    , 'date_sub(current_date("America/Sao_Paulo"), interval 1 day)'
  ]


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  +persist_docs:
    relation: true
    columns: true
  stone_case:
    staging:
      +materialized: table
      +schema: staging

    marts_local:
      materialized: table
      +schema: marts_local
      +tags: conformed
      
    marts_analytics:
      materialized: table
      +schema: marts_analytics
      +tags: conformed
      transactions:
        transactions_facts:
          transactions_facts_ton:
            +tags: ton_stone
# models:
#   stone_case:
#     # Applies to all files under models/example/
#     ton_stone:
#       materialized: table
